using System.Security.Cryptography;
using System.Text;

namespace Lumos.Core.Recovery;

/// <summary>
/// The Lumos recovery code: a high-entropy secret GENERATED BY THE APP that can
/// unwrap the vault's cipher key independently of the master password.
///
/// Why generated and not user-chosen: a recovery secret is a second door to the
/// same data, so it must be at least as strong as the first. A user-invented
/// word or phrase would be far weaker than a master password and would become
/// the cheapest way in. Generating it removes that choice — and the entropy
/// argument — entirely.
///
/// Format: 30 characters from a 30-symbol unambiguous alphabet, displayed in
/// six dash-separated groups of five:
///
///     ABCDE-FGHJK-MNPQR-STVWX-YZ234-56789
///
/// That is 30 * log2(30) ~= 147 bits — far beyond brute force, online or off.
///
/// The alphabet omits characters people confuse when copying from paper:
/// no 0/O, no 1/I/L, and no U (which is easily read as V in handwriting).
///
/// IMPORTANT: Lumos never stores the recovery code. Only a key DERIVED from it
/// (Argon2id) is used, and only its wrap of the cipher key is written to the
/// header. If the user loses both the master password and the recovery code,
/// the vault is unrecoverable — by design, and by anyone including us.
/// </summary>
public static class RecoveryCode
{
    /// <summary>Unambiguous 30-symbol alphabet. No 0/O, 1/I/L, or U.</summary>
    private const string Alphabet = "ABCDEFGHJKMNPQRSTVWXYZ23456789";

    /// <summary>Number of significant characters (excluding dashes).</summary>
    public const int CharacterCount = 30;

    /// <summary>Characters per dash-separated display group.</summary>
    public const int GroupSize = 5;

    /// <summary>Approximate entropy of a generated code, in bits (~147).</summary>
    public static double EntropyBits => CharacterCount * Math.Log2(Alphabet.Length);

    /// <summary>
    /// Generate a fresh recovery code in display form (with dashes).
    ///
    /// Uses rejection sampling rather than modulo. 256 is not a multiple of 30,
    /// so `randomByte % 30` would make the first 16 letters of the alphabet
    /// slightly more likely than the rest — a small but pointless bias in a
    /// value whose entire job is to be unguessable.
    /// </summary>
    public static string Generate()
    {
        // Largest multiple of the alphabet length that fits in a byte.
        // Bytes at or above this are discarded and redrawn.
        const int limit = 256 - (256 % 30);   // 240

        var chars = new char[CharacterCount];
        var buffer = new byte[1];
        var produced = 0;

        while (produced < CharacterCount)
        {
            RandomNumberGenerator.Fill(buffer);
            if (buffer[0] >= limit) continue;      // reject and redraw
            chars[produced++] = Alphabet[buffer[0] % Alphabet.Length];
        }

        var result = Format(new string(chars));
        Array.Clear(chars);
        return result;
    }

    /// <summary>
    /// Normalise user input into the canonical 30-character form used for key
    /// derivation, or null if it isn't a well-formed code.
    ///
    /// Tolerates the things people actually do: lower case, missing or extra
    /// dashes, spaces, and leading/trailing whitespace. Deliberately does NOT
    /// auto-correct confusable characters (O to 0 and so on) — silently
    /// rewriting a user's input would turn a typo into a confusing
    /// "wrong code" instead of an obvious one.
    /// </summary>
    public static string? Normalize(string? input)
    {
        if (string.IsNullOrWhiteSpace(input)) return null;

        var sb = new StringBuilder(CharacterCount);
        foreach (var raw in input)
        {
            if (raw is '-' or ' ' or '\t' or '\r' or '\n') continue;

            var ch = char.ToUpperInvariant(raw);
            if (!Alphabet.Contains(ch)) return null;    // character not in alphabet

            if (sb.Length == CharacterCount) return null;  // too long
            sb.Append(ch);
        }

        return sb.Length == CharacterCount ? sb.ToString() : null;
    }

    /// <summary>
    /// True if the input normalises to a well-formed code. This is a SHAPE
    /// check only — it says nothing about whether the code opens any vault.
    /// </summary>
    public static bool IsWellFormed(string? input) => Normalize(input) is not null;

    /// <summary>
    /// Insert dashes into a canonical 30-character code for display.
    /// </summary>
    public static string Format(string canonical)
    {
        ArgumentException.ThrowIfNullOrEmpty(canonical);
        if (canonical.Length != CharacterCount)
            throw new ArgumentException(
                $"Recovery code must be {CharacterCount} characters.", nameof(canonical));

        var sb = new StringBuilder(CharacterCount + (CharacterCount / GroupSize) - 1);
        for (var i = 0; i < canonical.Length; i += GroupSize)
        {
            if (i > 0) sb.Append('-');
            sb.Append(canonical, i, GroupSize);
        }
        return sb.ToString();
    }
}
